# Generated by Django 4.2.7 on 2023-11-24 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('profile_img', models.ImageField(upload_to='pictures')),
                ('license_number', models.IntegerField()),
                ('district', models.CharField(max_length=50)),
            ],
        ),
    ]
