# Generated by Django 4.2.7 on 2023-11-24 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('license_number', models.IntegerField()),
                ('license_image', models.ImageField(upload_to='pictures')),
                ('vehicle', models.CharField(default='Car', max_length=5)),
                ('experience', models.IntegerField(default=0)),
            ],
        ),
    ]
